DISCORD_API_BASE_URL = "https://discord.com/api"

DISCORD_BASE_AUTH_URL = DISCORD_API_BASE_URL + "/oauth2/authorize"
DISCORD_TOKEN_URL = DISCORD_API_BASE_URL + "/oauth2/token"
DISCORD_TOKEN_REVOCATION_URL = DISCORD_API_BASE_URL + "/oauth2/token/revoke"

DISCORD_USER_BASE_URL = DISCORD_API_BASE_URL + "/users/@me"
DISCORD_USER_GUILDS_URL = DISCORD_USER_BASE_URL + "/guilds"

DISCORD_IMAGE_BASE_URL = "https://cdn.discordapp.com"

DISCORD_IMAGE_FORMAT = "png"
DISCORD_ANIMATED_IMAGE_FORMAT = "gif"

DISCORD_USER_AVATAR_BASE_URL = DISCORD_IMAGE_BASE_URL + "/avatars/{user_id}/{avatar_hash}.{format}"
DISCORD_DEFAULT_USER_AVATAR_BASE_URL = DISCORD_IMAGE_BASE_URL + "/embed/avatars/{modulo5}.png"
DISCORD_GUILD_ICON_BASE_URL = DISCORD_IMAGE_BASE_URL + "/icons/{guild_id}/{icon_hash}.{format}"

UNICODE_ASCII_CHARACTER_SET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
